name: ROS2 nodes

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions: {}

jobs:
  ros2_node:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        release: [humble, jazzy]
    container: osrf/ros:${{ matrix.release }}-desktop
    steps:
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@0d6a7d60b009d01c9e7523be22153ff8f19460d3 # v2.2.0
        with:
          cmake-version: "3.25.x"
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Import dependencies
        working-directory: ros2
        run: vcs import src < vegvisir.repos
      - name: Run colcon
        working-directory: ros2
        run: source /opt/ros/${{ matrix.release }}/setup.bash && colcon build --event-handlers console_direct+
        shell: bash
